### ISSUE TITLE
Test Case validation are not being performed due to an error

### ISSUE THREAD

**Issue by agalaguz** [gsmainclusivetechlab/interop-test-platform#262] opened 2020-07-31 15:04 UTC
Issue found on http://staging.interop.gsmainclusivetechlab.io/sessions/72/test-cases/15/test-runs/499/1

Test Case validation are not being performed due to an error
`Non-static method SebastianBergmann\Timer\Timer::start() should not be called statically`

## Steps to reproduce

1. Login as any admin e.g. superadmin@gsma.com / qzRBHEzStdG8XWhy
2. Create any Session and execute any Test Case
3. See an error on every Test Step
![image](https://user-images.githubusercontent.com/16337770/89048218-3223a100-d358-11ea-98ac-5a9248e0d0d9.png)

## Expected outcome

I see Schema and Assertions validations

## Actual outcome

I see `Non-static method SebastianBergmann\Timer\Timer::start() should not be called statically`

**Comment by jcakokorev** [comment] 2020-07-31 15:33
Looks like there is a some big change pushed to Timer packagehttps://github.com/sebastianbergmann/php-timer#basic-timing, so we are need to update our usage of this class correctly in https://github.com/gsmainclusivetechlab/interop-test-platform/blob/develop/src/app/Testing/TestCase.php#L42 (from static call)

**Comment by brunosmm** [comment] 2020-07-31 15:42
Is this related to a lib update? Can we downgrade the lib and merge to the develop and open an issue to upgrade the lib?
@cjol, can you fup on this?
@eudisley this should impact your testing on new test cases.

**Comment by eudisley** [comment] 2020-07-31 15:55
Yes @brunosmm , I just tested a new test case and got this same error. 
I think it is just to initiate (new) the variable cause we are tying to use a non static method statically. 
Instead of: Timer::start()
$timeStart = new Timer();
$timeStart->start();

But... I quick solution could be the downgrade and check this lib issue in a separated branch. ;)

**Comment by cjol** [comment] 2020-08-03 16:16
Seems like this issue is reappearing, but giving this error instead:

```
{
    "message": "Timer::start() has to be called before Timer::stop()"
}
```
@jcakokorev have you seen this? @eudisley can give a full reproduction if necessary

**Comment by jcakokorev** [comment] 2020-08-03 19:51
@cjol interesting...first time seeing this. @eudisley could you please provide more info? Where did you get this?

**Comment by eudisley** [comment] 2020-08-03 20:39
Hi @jcakokorev I got this message on Postman, trying to run a testcase. And also, it is on the session I tried to execute the test case.
![Cash-Out - Test 03_08_2020 - Interoperability Test Platform - GSMA - Google Chrome 8_3_2020 9_37_49 PM (2)](https://user-images.githubusercontent.com/4050924/89225204-c0568c00-d5d1-11ea-9e40-9fa3390baf08.png)

**Comment by eudisley** [comment] 2020-08-06 15:43
The error is fixed so I will close this issue.

**Closed** 2020-08-06 15:43 UTC
Labels: bug
